# Generated by Django 4.2.7 on 2024-05-01 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pair_paws_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pair_paws_app.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pets',
            field=models.ManyToManyField(blank=True, related_name='owners', to='pair_paws_app.pet'),
        ),
    ]
